# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

[[main]]
  name = "About"
  url = "about/"
  weight = 9

#[[main]]
 # name = "Posts"
 # url = "#posts"
 # weight = 10

#[[main]]
 # name = "Projects"
 # url = "#projects"
 # weight = 20
 
[[main]]
  name = "Research"
  url = "research/"
  identifier = "research"
  weight = 10

[[main]]
  name = "Publications"
  url = "publication/"
  parent = "research"
  weight = 11

[[main]]
  name = "Presentations"
  url = "talk/"
  parent = "research"
  weight = 12

[[main]]
  name = "Ongoing Projects"
  url = "research/"
  parent = "research"
  weight = 13
  
[[main]]
   name = "Teaching"
   identifier = "teaching"
   weight = 20
  
[[main]]
   name = "Experience"
   url = "teaching/"
   parent = "teaching"
   weight = 21

[[main]]
   name = "Course Materials"
   url = "courses/"
   parent = "teaching"
   weight = 22

[[main]]
   name = "Blog"
   url = "post/"
   weight = 70

[[main]]
   name = "Packages"
   url = "code/"
   weight = 80

[[main]]
   name = "Data"
   url = "DataViz/"
   weight = 90

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 100


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "files/CV.pdf"
  weight = 100
