# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

[[main]]
  name = "About"
  url = "about/"
  weight = 9

#[[main]]
 # name = "Posts"
 # url = "#posts"
 # weight = 10

#[[main]]
 # name = "Projects"
 # url = "#projects"
 # weight = 20

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 10

[[main]]
  name = "Presentations"
  url = "talk/"
  weight = 20
  
[[main]]
  name = "Research"
  url = "research/"
  weight = 50

[[main]]
   name = "Teaching"
   url = "teaching/"
   weight = 60
   
[[main]]
   name = "Blog"
   url = "post/"
   weight = 70

[[main]]
   name = "Packages"
   url = "code/"
   weight = 80

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "files/CV.pdf"
  weight = 100
